# This is a basic workflow to help you get started with Actions

name: Generate data

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - name: Run a multi-line script
        working-directory: ./data
        run: |
          npm install
          node index.js
