name: Generate data daily

on:
  push:
  schedule:
    - cron: "* 15 * * *"

defaults:
  run:
    working-directory: data

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: node index.js