name: Generate data daily

on:
  push:
  schedule:
    - cron: "* * * * *"

defaults:
  run:
    shell: bash
    working-directory: ./data

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Generate data
        runs:
          using: 'node12'
          main: 'index.js'