name: Generate data daily

on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd data
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Generate data
        run: |
        npm install
        node index.js 