name: Run Node.js script on a schedule

on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd data
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: | 
        npm install
        node index.js