name: Generate data daily

on:
  push:
  schedule:
    - cron: "* * * * *"

defaults:
  run:
    shell: bash
    working-directory: data

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Generate data
        run: |
          npm install
          node index.js